services:
  pkvault:
    image: ghcr.io/chnapy/pkvault:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pkvault
    ports:
      - "3000:3000"
    volumes:
      # Note: if you update settings paths, you should update them here too
      - ./pkvault-data/config:/app/backend/config
      - ./pkvault-data/db:/app/backend/db
      - ./pkvault-data/storage:/app/backend/storage
      - ./pkvault-data/backup:/app/backend/backup
      - ./pkvault-data/logs:/app/backend/logs
      - ./pkvault-data/saves:/app/backend/saves # saves can be somewhere else, no constraints
